---
name: pytest CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"
    env:
      USING_COVERAGE: '3.9'
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - name: "checkout algorand node repo"
        uses: "actions/checkout@v2"
        with:
          repository: algorand/sandbox
          path: sandbox
      - name: "print ls"
        run: ls
      - name: "pwd"
        run: pwd
      - name: "launch algorand local node"
        run: |
          cd sandbox
          script -e -c "./sandbox up -v dev"
          script -e -c "./sandbox reset -v" 
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade tox tox-gh-actions    

      - name: "Run tox targets for ${{ matrix.python-version }}"
        run:
          tox -e py39

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
